#!/usr/bin/env bash

set -eo pipefail

echo -e "\033[0;32m--- Run format, lint, and type checks ---\033[0m"
vp check --fix

echo -e "\033[0;32m--- Run knip ---\033[0m"
knip

echo -e "\033[0;32m--- Run secretlint ---\033[0m"
secretlint "**/*"
